/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace BloodChainRecord {
      
    export type DonationRecordStruct = {donationId: string, donorId: string, bloodBankId: string, bloodType: string, units: BigNumberish, status: string, timestamp: BigNumberish, exists: boolean}

    export type DonationRecordStructOutput = [donationId: string, donorId: string, bloodBankId: string, bloodType: string, units: bigint, status: string, timestamp: bigint, exists: boolean] & {donationId: string, donorId: string, bloodBankId: string, bloodType: string, units: bigint, status: string, timestamp: bigint, exists: boolean }
  

    export type RequestRecordStruct = {requestId: string, hospitalId: string, bloodBankId: string, bloodType: string, units: BigNumberish, status: string, timestamp: BigNumberish, exists: boolean}

    export type RequestRecordStructOutput = [requestId: string, hospitalId: string, bloodBankId: string, bloodType: string, units: bigint, status: string, timestamp: bigint, exists: boolean] & {requestId: string, hospitalId: string, bloodBankId: string, bloodType: string, units: bigint, status: string, timestamp: bigint, exists: boolean }
  
    }

  export interface BloodChainRecordInterface extends Interface {
    getFunction(nameOrSignature: "admin" | "donationIds" | "donations" | "getDonation" | "getRequest" | "recordBloodRequest" | "recordDonation" | "requestIds" | "requests" | "totalDonations" | "totalRequests"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DonationRecorded" | "RequestRecorded"): EventFragment;

    encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'donationIds', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'donations', values: [string]): string;
encodeFunctionData(functionFragment: 'getDonation', values: [string]): string;
encodeFunctionData(functionFragment: 'getRequest', values: [string]): string;
encodeFunctionData(functionFragment: 'recordBloodRequest', values: [string, string, string, string, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'recordDonation', values: [string, string, string, string, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'requestIds', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'requests', values: [string]): string;
encodeFunctionData(functionFragment: 'totalDonations', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalRequests', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'donationIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'donations', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDonation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordBloodRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordDonation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requests', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalDonations', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRequests', data: BytesLike): Result;
  }

  
    export namespace DonationRecordedEvent {
      export type InputTuple = [donationId: string, donorId: string, bloodBankId: string, bloodType: string, units: BigNumberish, status: string, timestamp: BigNumberish];
      export type OutputTuple = [donationId: string, donorId: string, bloodBankId: string, bloodType: string, units: bigint, status: string, timestamp: bigint];
      export interface OutputObject {donationId: string, donorId: string, bloodBankId: string, bloodType: string, units: bigint, status: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RequestRecordedEvent {
      export type InputTuple = [requestId: string, hospitalId: string, bloodBankId: string, bloodType: string, units: BigNumberish, status: string, timestamp: BigNumberish];
      export type OutputTuple = [requestId: string, hospitalId: string, bloodBankId: string, bloodType: string, units: bigint, status: string, timestamp: bigint];
      export interface OutputObject {requestId: string, hospitalId: string, bloodBankId: string, bloodType: string, units: bigint, status: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BloodChainRecord extends BaseContract {
    
    connect(runner?: ContractRunner | null): BloodChainRecord;
    waitForDeployment(): Promise<this>;

    interface: BloodChainRecordInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    donationIds: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    donations: TypedContractMethod<
      [arg0: string, ],
      [[string, string, string, string, bigint, string, bigint, boolean] & {donationId: string, donorId: string, bloodBankId: string, bloodType: string, units: bigint, status: string, timestamp: bigint, exists: boolean }],
      'view'
    >
    

    
    getDonation: TypedContractMethod<
      [donationId: string, ],
      [BloodChainRecord.DonationRecordStructOutput],
      'view'
    >
    

    
    getRequest: TypedContractMethod<
      [requestId: string, ],
      [BloodChainRecord.RequestRecordStructOutput],
      'view'
    >
    

    
    recordBloodRequest: TypedContractMethod<
      [requestId: string, hospitalId: string, bloodBankId: string, bloodType: string, units: BigNumberish, status: string, ],
      [void],
      'nonpayable'
    >
    

    
    recordDonation: TypedContractMethod<
      [donationId: string, donorId: string, bloodBankId: string, bloodType: string, units: BigNumberish, status: string, ],
      [void],
      'nonpayable'
    >
    

    
    requestIds: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    requests: TypedContractMethod<
      [arg0: string, ],
      [[string, string, string, string, bigint, string, bigint, boolean] & {requestId: string, hospitalId: string, bloodBankId: string, bloodType: string, units: bigint, status: string, timestamp: bigint, exists: boolean }],
      'view'
    >
    

    
    totalDonations: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalRequests: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'donationIds'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'donations'): TypedContractMethod<
      [arg0: string, ],
      [[string, string, string, string, bigint, string, bigint, boolean] & {donationId: string, donorId: string, bloodBankId: string, bloodType: string, units: bigint, status: string, timestamp: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getDonation'): TypedContractMethod<
      [donationId: string, ],
      [BloodChainRecord.DonationRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRequest'): TypedContractMethod<
      [requestId: string, ],
      [BloodChainRecord.RequestRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'recordBloodRequest'): TypedContractMethod<
      [requestId: string, hospitalId: string, bloodBankId: string, bloodType: string, units: BigNumberish, status: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordDonation'): TypedContractMethod<
      [donationId: string, donorId: string, bloodBankId: string, bloodType: string, units: BigNumberish, status: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestIds'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'requests'): TypedContractMethod<
      [arg0: string, ],
      [[string, string, string, string, bigint, string, bigint, boolean] & {requestId: string, hospitalId: string, bloodBankId: string, bloodType: string, units: bigint, status: string, timestamp: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'totalDonations'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalRequests'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'DonationRecorded'): TypedContractEvent<DonationRecordedEvent.InputTuple, DonationRecordedEvent.OutputTuple, DonationRecordedEvent.OutputObject>;
getEvent(key: 'RequestRecorded'): TypedContractEvent<RequestRecordedEvent.InputTuple, RequestRecordedEvent.OutputTuple, RequestRecordedEvent.OutputObject>;

    filters: {
      
      'DonationRecorded(string,string,string,string,uint256,string,uint256)': TypedContractEvent<DonationRecordedEvent.InputTuple, DonationRecordedEvent.OutputTuple, DonationRecordedEvent.OutputObject>;
      DonationRecorded: TypedContractEvent<DonationRecordedEvent.InputTuple, DonationRecordedEvent.OutputTuple, DonationRecordedEvent.OutputObject>;
    

      'RequestRecorded(string,string,string,string,uint256,string,uint256)': TypedContractEvent<RequestRecordedEvent.InputTuple, RequestRecordedEvent.OutputTuple, RequestRecordedEvent.OutputObject>;
      RequestRecorded: TypedContractEvent<RequestRecordedEvent.InputTuple, RequestRecordedEvent.OutputTuple, RequestRecordedEvent.OutputObject>;
    
    };
  }