/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BloodChainRecord } from './BloodChainRecord.js';
export type { MedicalRecordRegistry } from './MedicalRecordRegistry.js';
export * as factories from './factories/index.js';
export { BloodChainRecord__factory } from './factories/BloodChainRecord__factory.js';
export { MedicalRecordRegistry__factory } from './factories/MedicalRecordRegistry__factory.js';