/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace MedicalRecordRegistry {
      
    export type AccessEntryStruct = {patient: AddressLike, doctor: AddressLike, granted: boolean, timestamp: BigNumberish}

    export type AccessEntryStructOutput = [patient: string, doctor: string, granted: boolean, timestamp: bigint] & {patient: string, doctor: string, granted: boolean, timestamp: bigint }
  

    export type RecordEntryStruct = {sha256Hash: BytesLike, ipfsHash: string, patient: AddressLike, uploader: AddressLike, timestamp: BigNumberish, isVerified: boolean}

    export type RecordEntryStructOutput = [sha256Hash: string, ipfsHash: string, patient: string, uploader: string, timestamp: bigint, isVerified: boolean] & {sha256Hash: string, ipfsHash: string, patient: string, uploader: string, timestamp: bigint, isVerified: boolean }
  
    }

  export interface MedicalRecordRegistryInterface extends Interface {
    getFunction(nameOrSignature: "admin" | "getAccessEntry" | "getAccessLogLength" | "getPatientRecords" | "getRecord" | "logAccess" | "registerRecord" | "transferAdmin" | "verifyIntegrity" | "verifyRecord"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AccessChanged" | "AdminTransferred" | "RecordRegistered" | "RecordVerified"): EventFragment;

    encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAccessEntry', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAccessLogLength', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPatientRecords', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getRecord', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'logAccess', values: [AddressLike, AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'registerRecord', values: [BytesLike, string, AddressLike]): string;
encodeFunctionData(functionFragment: 'transferAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'verifyIntegrity', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'verifyRecord', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAccessEntry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAccessLogLength', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPatientRecords', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'logAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyIntegrity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyRecord', data: BytesLike): Result;
  }

  
    export namespace AccessChangedEvent {
      export type InputTuple = [patient: AddressLike, doctor: AddressLike, granted: boolean, timestamp: BigNumberish];
      export type OutputTuple = [patient: string, doctor: string, granted: boolean, timestamp: bigint];
      export interface OutputObject {patient: string, doctor: string, granted: boolean, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AdminTransferredEvent {
      export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
      export type OutputTuple = [previousAdmin: string, newAdmin: string];
      export interface OutputObject {previousAdmin: string, newAdmin: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RecordRegisteredEvent {
      export type InputTuple = [sha256Hash: BytesLike, ipfsHash: string, patient: AddressLike, uploader: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [sha256Hash: string, ipfsHash: string, patient: string, uploader: string, timestamp: bigint];
      export interface OutputObject {sha256Hash: string, ipfsHash: string, patient: string, uploader: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RecordVerifiedEvent {
      export type InputTuple = [sha256Hash: BytesLike, verifiedBy: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [sha256Hash: string, verifiedBy: string, timestamp: bigint];
      export interface OutputObject {sha256Hash: string, verifiedBy: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MedicalRecordRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): MedicalRecordRegistry;
    waitForDeployment(): Promise<this>;

    interface: MedicalRecordRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getAccessEntry: TypedContractMethod<
      [index: BigNumberish, ],
      [MedicalRecordRegistry.AccessEntryStructOutput],
      'view'
    >
    

    
    getAccessLogLength: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getPatientRecords: TypedContractMethod<
      [patient: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    getRecord: TypedContractMethod<
      [sha256Hash: BytesLike, ],
      [MedicalRecordRegistry.RecordEntryStructOutput],
      'view'
    >
    

    
    logAccess: TypedContractMethod<
      [patient: AddressLike, doctor: AddressLike, granted: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    registerRecord: TypedContractMethod<
      [sha256Hash: BytesLike, ipfsHash: string, patient: AddressLike, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferAdmin: TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    verifyIntegrity: TypedContractMethod<
      [sha256Hash: BytesLike, ],
      [[boolean, boolean, bigint] & {exists: boolean, isVerified: boolean, timestamp: bigint }],
      'view'
    >
    

    
    verifyRecord: TypedContractMethod<
      [sha256Hash: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAccessEntry'): TypedContractMethod<
      [index: BigNumberish, ],
      [MedicalRecordRegistry.AccessEntryStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getAccessLogLength'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPatientRecords'): TypedContractMethod<
      [patient: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getRecord'): TypedContractMethod<
      [sha256Hash: BytesLike, ],
      [MedicalRecordRegistry.RecordEntryStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'logAccess'): TypedContractMethod<
      [patient: AddressLike, doctor: AddressLike, granted: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerRecord'): TypedContractMethod<
      [sha256Hash: BytesLike, ipfsHash: string, patient: AddressLike, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferAdmin'): TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyIntegrity'): TypedContractMethod<
      [sha256Hash: BytesLike, ],
      [[boolean, boolean, bigint] & {exists: boolean, isVerified: boolean, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'verifyRecord'): TypedContractMethod<
      [sha256Hash: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AccessChanged'): TypedContractEvent<AccessChangedEvent.InputTuple, AccessChangedEvent.OutputTuple, AccessChangedEvent.OutputObject>;
getEvent(key: 'AdminTransferred'): TypedContractEvent<AdminTransferredEvent.InputTuple, AdminTransferredEvent.OutputTuple, AdminTransferredEvent.OutputObject>;
getEvent(key: 'RecordRegistered'): TypedContractEvent<RecordRegisteredEvent.InputTuple, RecordRegisteredEvent.OutputTuple, RecordRegisteredEvent.OutputObject>;
getEvent(key: 'RecordVerified'): TypedContractEvent<RecordVerifiedEvent.InputTuple, RecordVerifiedEvent.OutputTuple, RecordVerifiedEvent.OutputObject>;

    filters: {
      
      'AccessChanged(address,address,bool,uint256)': TypedContractEvent<AccessChangedEvent.InputTuple, AccessChangedEvent.OutputTuple, AccessChangedEvent.OutputObject>;
      AccessChanged: TypedContractEvent<AccessChangedEvent.InputTuple, AccessChangedEvent.OutputTuple, AccessChangedEvent.OutputObject>;
    

      'AdminTransferred(address,address)': TypedContractEvent<AdminTransferredEvent.InputTuple, AdminTransferredEvent.OutputTuple, AdminTransferredEvent.OutputObject>;
      AdminTransferred: TypedContractEvent<AdminTransferredEvent.InputTuple, AdminTransferredEvent.OutputTuple, AdminTransferredEvent.OutputObject>;
    

      'RecordRegistered(bytes32,string,address,address,uint256)': TypedContractEvent<RecordRegisteredEvent.InputTuple, RecordRegisteredEvent.OutputTuple, RecordRegisteredEvent.OutputObject>;
      RecordRegistered: TypedContractEvent<RecordRegisteredEvent.InputTuple, RecordRegisteredEvent.OutputTuple, RecordRegisteredEvent.OutputObject>;
    

      'RecordVerified(bytes32,address,uint256)': TypedContractEvent<RecordVerifiedEvent.InputTuple, RecordVerifiedEvent.OutputTuple, RecordVerifiedEvent.OutputObject>;
      RecordVerified: TypedContractEvent<RecordVerifiedEvent.InputTuple, RecordVerifiedEvent.OutputTuple, RecordVerifiedEvent.OutputObject>;
    
    };
  }