services:
  - type: web
    name: bloodchain-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: AES_SECRET_KEY
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: PINATA_API_KEY
        sync: false
      - key: PINATA_SECRET_KEY
        sync: false
      - key: PINATA_GATEWAY
        value: https://gateway.pinata.cloud
      - key: CONTRACT_ADDRESS
        sync: false
      - key: SEPOLIA_RPC_URL
        sync: false
      - key: SEPOLIA_PRIVATE_KEY
        sync: false
