/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BloodChainRecord__factory } from './BloodChainRecord__factory.js';
export { MedicalRecordRegistry__factory } from './MedicalRecordRegistry__factory.js';